### PR TITLE
Added optional flag on UpdateRecipients method to enable resend_envelope...

### PR DESCRIPTION
**Pull request by peterlord**
I needed to be able to update a recipient of an envelope and always send an email. I found the parameter required to do this (resend_envelope) in the API docs and have added it as an optional argument to the UpdateRecipients method.

Thanks.

### CODE REVIEW

**Comment by InbarGazit** [comment]
Thanks @peterlord , note we have a SendReminder() method that would do that, but it's separate from updating a recipient (as in your case). Might be a nice thing to have the ability to do that in conjecture with the update as you suggested...

**Comment by peterlord** [comment]
Yes I saw the SendReminder() method but as far as I understand that sends the reminder to all recipients? This change also gives a method of re-sending the email to just one of the recipients. Thanks.

**Comment by InbarGazit** [comment]
ok, took your change. thanks @peterlord , let me know if you have other questions!

**Comment by InbarGazit** [comment]
@peterlord , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Pull request merged**
