### PR TITLE
added support for getting envelopeInfo based on an envelopeId

### PR DESCRIPTION
**Pull request by loredanalehadus**

### CODE REVIEW

**Comment by InbarGazit** [comment]
great, thanks so much @loredanalehadus this is more new functionality, right?
does it work for you? just making sure before I merge. thanks!

**Comment by loredanalehadus** [comment]
Hello, 

Yes, it's working. I'm already using this in my application.

**Comment by loredanalehadus** [comment]
Hey, 

It seems that including the dll in the project works but only on my machine. When I deploy it the nuget packages restore overrides the library i included. How much time do you think you'll need in order to get a new nuget? I will apreciate it if it will be asap. 

Thanks, 
Loredana

**Comment by InbarGazit** [comment]
sure thing, will try to get this out today!

**Comment by InbarGazit** [comment]
this one has conflicts, I'll need to resolve them later, not sure why this happened.

**Comment by loredanalehadus** [comment]
Let me know if you need help with it. Maybe i can merge on my branch and make a new pull request?

**Comment by InbarGazit** [comment]
I think we're good. I had a conflict in envelope.cs that seems to be stylistic and only like spaces and such. please check latest master branch and let me know

**Comment by InbarGazit** [comment]
@loredanalehadus I just pushed a new nuget (version 1.7.0) with your changes. Can you confirm it's working for you when you deploy? thanks!

**Pull request merged**
