### PR TITLE
First pull request, heh

### PR DESCRIPTION
**Pull request by gonemad83**
Use it, don't use it.  Whatever.  I will continue to add functionality as I require it.

### CODE REVIEW

**Comment by sirsquidness** [comment]
The latter of the two commits in this adds this to the DocuSign.Integrations.Client.csproj file
<Compile Include="TextTab.cs" />

TextTab.cs isn't included in the commits, so this causes the build to fail.

**Comment by InbarGazit** [comment]
thanks @sirsquidness , @gonemad83 can you add TextTab.cs file?

**Comment by gonemad83** [comment]
@sirsquidness Sorry about that.   @InbarGazit I have added it to my current fork. Not sure what the best way merge it.  There are also some additional changes I have made in my version.  Let me know what you want to do. TextTab.cs should be easy enough to grab though.

**Comment by gonemad83** [comment]
@InbarGazit My version has removed the proxy properties as well because it wasn't being used and shouldn't be used.  Setting the proxy via configuration is preferable.

**Comment by InbarGazit** [comment]
@gonemad83 , can you create a new branch where you just add that file? or you can post the file here and I can add it

**Comment by powdernine** [comment]
I've been perusing this repo too. To get it to build I added @gonemad83 's file here:

https://raw.githubusercontent.com/gonemad83/DocuSign-.NET-Client/master/DocuSign.Integrations.Client/TextTab.cs

**Comment by InbarGazit** [comment]
this was now added, please pull latest and you should be good

**Pull request merged**
