### PR TITLE
ADD eventNotification.signMessageWithX509Cert

### PR DESCRIPTION
**Pull request by lAnubisl**
Now clients can request event notification messages to be signed.

### CODE REVIEW

**Comment by lAnubisl** [comment]
According to DocuSign Specification (https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Send%20an%20Envelope.htm?Highlight=signMessageWithX509Cert) this option is used to sign push messages with an X509 certificate. As I understand any notificationListener needs to rely on DocuSign certificate in order to not accept requests from anybody.

**Comment by InbarGazit** [comment]
ok, but did you actually try this and it worked as you expected? I want to make sure we're doing this right

**Comment by lAnubisl** [comment]
Honestly I made this change because I need this feature and existing library was not implementing that. I'm sure that request to DocuSign not contains the property as described in specification and accepts 'Create envelope' successfully. I had no chance to make sure that DocuSign actually sign messages with certificate, so pull request can wait until I be sure 100% all reature works.

**Comment by InbarGazit** [comment]
ok, I'll wait for you to confirm before I merge. thanks

**Comment by InbarGazit** [comment]
@lAnubisl just noticed that we never finished this one. Did you confirm this works correctly?

**Comment by lAnubisl** [comment]
It's scheduled but not critical for our project right now. I'm sure that with this parameter turned on the envelope is accepted by docusign but I did not had a chance yet to test the whole request - push back cycle. I will comment here when it's done.

**Comment by InbarGazit** [comment]
any update on this?

**Comment by lAnubisl** [comment]
Sorry @InbarGazit we still didn't have a chance to validate how it works because DocuSign didn't provide some details yet but we will do soon. We will not release our project without this feature and I will let you know when I 100% sure this feature works correctly. What can I say right now is that we haven't seen any regression since this change was implemented on our side.

**Comment by lAnubisl** [comment]
Now I can confirm that this feature works.

**Comment by lAnubisl** [comment]
Please review this one

**Comment by InbarGazit** [comment]
@lAnubisl can you make a new pull/branch based on latest with only this update? this has been out of sync with recent changes and cause merge issues

**Pull request closed without merging**
