### PR TITLE
Expose DocumentFields and Create Envelope with Document Objects

### PR DESCRIPTION
**Pull request by Patman0021**
- Created GetDocumentFields function.
- Added GetEnvelopeDocumentInfo with no parameters, since you're getting the document info from an instance of an envelope.
- Created CreateJson with List<Document> to be added to the EnvelopeCreate instead of a List<string> and startIndex.
- Created Create with the List<Byte[]> of file data and List<Document> of documents.

Envelope.json.cs
- Added DocumentFields class for json transmission of the document custom data.
- Added DocumentField for json transmission of one set of document custom data.
- Added a DocumentField array to the Document class so that its included in the outgoing json.

EnvelopeTest
- Created a static variable in the test class that is initialized during the ClassInitialize.
- Added EnvelopeCreateWithDocumentObjectsAndGetDocumentFieldsTest to test creating an envelope using document objects and getting the document fields from the documents.

### CODE REVIEW

**Comment by InbarGazit** [comment]
I'm going to update some of the top comments for the API users to get a bit more info

**Comment by InbarGazit** [comment]
@Patman0021  does this compile for you?

**Comment by InbarGazit** [comment]
@Patman0021 I reverted this change for now until we can figure this out so that people that clone this would have working code. thanks

**Comment by Patman0021** [comment]
Yep, i reapplied my changes and ran the test.  And it passed, so it compiled.

**Comment by InbarGazit** [comment]
are you using some special VS tool or some other weird thing? 
I mean, I had some examples for you of things that don't look like valid C# to me

**Comment by InbarGazit** [comment]
as an example:

req.Uri = $"{Login.BaseUrl}/envelopes/{EnvelopeId}/documents";

looks like some jQuery/C# combo. Not sure what this is. doesn't compile for me

**Comment by Patman0021** [comment]
Oh, I'm sorry, thats c#6, I can recode so that its the old style.

**Comment by InbarGazit** [comment]
yes, this has to be compatible for all developers with VS2013.
Please submit another update. sorry for the confusion

**Comment by Patman0021** [comment]
Oh no problem, completely my fault.  Once we went to VS2015, I never looked back.  Not so great when you're working with the community.

Creating the new pull request now.

**Comment by Patman0021** [comment]
I made a new pull request. I loaded it up in VS2013 and fixed all the "new" syntax. I apologize, between worrying about writing "community" code and it being my first foray into really using Git (we use TFS at work). The fact I was using brand new syntax slipped my mind!  Ah well, I should be better next time ;)

**Pull request merged**
