### PR TITLE
Remove MaxBlurbSize

### PR DESCRIPTION
**Pull request by lAnubisl**
According to https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Send%20an%20Envelope.htm emailBlurb is up to 10000 characters

It's not library's responsibility to validate user's input.

I checked this change on my project

### CODE REVIEW

**Comment by InbarGazit** [comment]
I actually disagree with this statement "It's not library's responsibility to validate user's input"
now if an empty blurb is allowed - than this change is fine. Otherwise - I don't understand why would you want to make this change?

**Comment by InbarGazit** [comment]
this is also potentially breaking change

**Comment by lAnubisl** [comment]
>I actually disagree with this statement "It's not library's responsibility to validate user's input"
Library does not control other field's length. So why it cut's EmailBlurb?

>Otherwise - I don't understand why would you want to make this change?
Originally I made this change because I wanted to put 10.000 characters in EmailBlurb. Client library just cut my message without any notification! No errors, no warnings, I just lost 90% of all message.

>this is also potentially breaking change
What exactly is breaking in this change? Did I forget some case?

**Comment by InbarGazit** [comment]
Sorry @lAnubisl are you saying that once you made this change you're able to pass 10,000 characters in the blurb and you see all 10,000 characters in the email? I just need to validate this. There's definitely some limit, maybe we got the wrong one, so we should just increase the number, but not having an upper limit is not a good idea.

**Comment by lAnubisl** [comment]
As I pointed in my original message, correct. 10.000 characters and I saw them in my email. I don't see why you need this limit at all since DocuSign will validate the request on his side anyway. Again, this library does NOT validates any other field length so why do you think it is important to !!CUT!! user's input?

**Comment by InbarGazit** [comment]
let me check what is the limit and get back to you

**Comment by InbarGazit** [comment]
ok, you're right, the upper limit is 10,000 and not 1000. We simply missed a zero. I understand your point about not validating other fields, but this code with 10,000 would work just fine so I prefer to make the change from 1,000 to 10,000 and not remove this code completely. ok?

**Comment by lAnubisl** [comment]
Personally I can live with this, but I don't share your point of view.
Would you like me to make this change and send you another pull request or you will do this yourself?
If you will do this yourself please change the way how It's implemented. There is a nice String.Substring(Int32, Int32) function.

**Comment by InbarGazit** [comment]
please go ahead and make the change. I appreciate your help improving the library!

**Comment by lAnubisl** [comment]
Please remove this pull request

**Comment by InbarGazit** [comment]
done

**Pull request closed without merging**
