### PR TITLE
Issue #56 - Added a method in Envelope.cs to do the prerequisite chec…

### PR DESCRIPTION
**Pull request by bojake**
…ks on member attributes.

Added a new method in the ConfigLoader to create the test account and updated tests to use this new method.
Issue #56 - Added try/catch in api method calls where missing.
Issue #56 - Removed use of embedded Login.BaseUrl in Uri settings of RequestInfo in API method calls.

This is a general consistency update and some functionality change. The BaseUrl is used as a trigger value to notify the developer invoke the Account.Login method prior to making api calls.

### CODE REVIEW

**Comment by InbarGazit** [comment]
@bojake  can you rename CreateTestAccount() to RetrieveTestAccount()? 
the reason is there's a way to actually create a new account from API given you use these distributor keys but what this method is doing is just gathering information so it's not scattered (Which is great) but I want to avoid confusion for future developers.

**Comment by bojake** [comment]
Create -> Retrieve : sure, then we should invoke the Login() on it too?

**Comment by InbarGazit** [comment]
it's invoked elsewhere in the actual test as part of other API calls, I believe, but it's not going to harm, so yes, sure.

**Comment by bojake** [comment]
this is ready for merge now.

**Comment by InbarGazit** [comment]
merged. thanks!

**Pull request merged**
