### PR TITLE
Change GetAccountsEnvelope to be regiona agnostic

### PR DESCRIPTION
**Pull request by srbrown1977**
We had an issue calling the GetAccountsEnvelopes method from machines in the UK region, where the DateTime.ToString() was passing a UK date format to the server, and causing an Exception.

The fix (and also sorted out UTC issues) was to specify the date time format when calling DateTime.ToString().

Not sure why the change below has picked up 299 changes.. the only change is actually within the GetAccountsEnvelopes method.

### CODE REVIEW

**Comment by InbarGazit** [comment]
thanks @srbrown1977  this looks like a reall good and useful change.
can you do this - can you do a new clone, make sure if you use VS that you don't change any line formatting, tabs, etc. so only the lines you changed show up as changes. Would be easier for everyone when looking at history. thanks!

**Comment by srbrown1977** [comment]
Struggling with the formatting.. will pick this up tomorrow :).. First time I've been dealing with GitHub.

**Comment by InbarGazit** [comment]
that's ok, let me know if I can help!

**Comment by nardin** [comment]
You click "Yes" in dialog


I have the same problem :)

**Comment by InbarGazit** [comment]
ok, so @nardin  you used VS but seems like @srbrown1977 just changed things using the web version of git? can you confirm

**Comment by srbrown1977** [comment]
I gave up on the VS2013 edit, as I wasn't able to commit a change without coming across the issue. (My compare tools on my local machine couldn't see any differences that the github compare saw).

I deleted that fork, and started from scratch again.  the second time around I did everything in the Browser window (Chrome).  Forked, and then edited the envelope.cs, and then commited.  The same spurious changes appeared in the diff :( ..  Could someone else try doing the same thing, just in the Browser.. I know I'm new to this, but I can't see what I can have done wrong. :(

Thanks
Steve

**Comment by InbarGazit** [comment]
@srbrown1977 Steve, I have checked in your change and put your name in the comment. Please get latest on master branch (or do a new clone) to see the change. 
let me know if this is working for you

**Comment by InbarGazit** [comment]
@srbrown1977 we released nuget version 1.7.1 with the help of @bojake and it includes your fix. Closing this issue, let me know if you need additional assistance

**Pull request closed without merging**
